name: Never Run This

on: 
  push:
    branches:
      - main  
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 1st step
        run: echo ${{ github.repositoryUrl}}
      - name: 2nd step
        run: |
          pwd
          ls -al
      - name: 3rd step create a file
        run: |
          echo "Hello World" > hello.txt
          echo "can you see me?" >> hello.txt
          cat hello.txt
      - name: 4th step
        run: |
          pwd
          ls -al
